name: build CALDP

on:
  workflow_dispatch:
    inputs:
      release:
        description: CALDP release (can also be `latest`, `stable`)
        type: string
        required: false
  workflow_call:
    inputs:
      release:
        description: CALDP release (can also be `latest`, `stable`)
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build CALDP `${{ inputs.release || 'latest' }}` (${{ matrix.runs-on }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
    defaults:
      run:
        shell: micromamba-shell {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: caldp-${{ runner.os }}
          environment-file: caldp/${{ inputs.release || 'latest' }}/latest-${{ runner.os == 'Linux' && 'linux' || 'macos' }}.yml
          init-shell: none
          generate-run-shell: true
      - run: pip list
